var farn = parseFloat(prompt("Enter a float type number:-" ));
var cels = parseFloat(prompt("Enter a  second flaot type number:-"));
var cels = (farn-32) * (5/9);
document.write("celsius =" + cels);

var cels = parseFloat(prompt("Enter a float type number:-" ));
var farn = parseFloat(prompt("Enter a  second flaot type number:-"));
var farn = (farn-32) * (5/9);
document.write("celsius =" + farn);

