// If/else ?????

/// switch ///

var num = prompt("Enter any number or digit is here:");
if (num == 0)
document.write("zero");
else if(num == 1)
document.write("One");
else if(num == 2)
document.write("two");
else if(num == 3)
document.write("Three");
else if(num == 4)
document.write("Four");
else if(num == 5)
document.write("Five");
else if(num == 6)
document.write("Six");
else
document.write("No Number Match is here:");

//Switch case code is here:-/////

 var num = prompt("Enter your user number :-");

 switch(num)
 {    
    case "0":
    document.write("zero");
    break;
     case "1":
    document.write("One");
    break;
     case "2":
    documentwrite("two");
    break;
    case "3":
    document.write("Three");
    break;
     case "4":
    document.write("Four");
    break;
     case "5":            
    document.write("Five");
    break;
     case "6":   
    document.write("Six");
    break; 
    default:    
    document.write("No Number Match is here:");
 }
