//IIFEs and function expression//

(function display(num1, num2)
{    var display  = num1 + num2;
    {
        console.log("num is=" +num);
    }
     

})()
 
display(); 


*****ARRAY***

var name1, name2, name3, name4, name5;
name1 = "noman";
name2 = "monir";
name3 = "vabi";
name4 = "nostlis";
name5 = "jklr";
document.write(name3);


var names = new Array(5);

names [1] = "noman";
names[2] = "monir";
names[3] = "vabi";
names[4] = "nostlis";
names[5] = "jklr";
document.write(names +"<br/>");
document.write(" Array Length is =" +names.length);
