
const varName =document.querySelector("div");

  div.addEventListener("click", function()
{
    console.log("click is occurd");
  
});

div.addEventListener("click", function()
{
    console.log("dbclick is occurd");
  
});

div.addEventListener("mousedown", function()
{
    console.log("mousedown is occurd");
  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
     <link rel="stylesheet" href="style.css">
    
</head>
<body>

    <div> 
        <P>  I am Noman Hasan </P>
    </div>
   
    <script src="index.js"></script>
</body>
</html>


///******js


console.clear();
div.addEventListener("mouseup", function()
{
    console.log("mouseup is occurd");
  
});

div.addEventListener("mousesenter", function()
{
    console.log("mousesente is occurd");
  
});

div.addEventListener("mouseleave", function()
{
    console.log("mouseleave is occurd");
  
});
div.addEventListener("mousemove", function()
{
    console.log("mousemove is occurd");
  
});
div.addEventListener("mouseover", function()
{
    console.log("mouseover is occurd");
  
});

/////**** style.css


div{
    background-color: red;
    height: 20rem;
    width: 20rem;
}


